#!/usr/bin/env python
import glob

from glue.ligolw import lsctables, utils

map_dict = { 
    "MAG-PART_SHIELD_CHAN1": "K1",
    "MAG-PART_SHIELD_CHAN2": "K2",
    "MAG-FULL_SHIELD_CHAN1": "K3",
    "MAG-FULL_SHIELD_CHAN2": "K4"
}

for dir in map_dict.keys():
    for fname in glob.glob("K1_new_inst/K1/%s_excesspower/*/*.xml.gz" % dir):
        xmldoc = utils.load_filename(fname)
        sngl_burst = lsctables.SnglBurstTable.get_table(xmldoc)
        #sngl_burst = table.get_table(fname, lsctables.SnglBurstTable.tableName)
        for sb in sngl_burst:
            sb.ifo = map_dict[dir]
        utils.write_filename(xmldoc, fname, gz=True)
